os: linux
dist: trusty
language: c

services:
  - docker

install:
  - curl -O -L "https://raw.githubusercontent.com/cherry-pick/cherry-images/v1/scripts/vmrun"
  - curl -O -L "https://raw.githubusercontent.com/cherry-pick/cherry-ci/v1/scripts/cherryci"
  - chmod +x "./vmrun" "./cherryci"

jobs:
  include:
    - stage: test
      script:
        - ./vmrun -- ../src/cherryci -d ../src/.cherryci -s c-util -m
    - script:
        - ./vmrun -T armv7hl -- ../src/cherryci -d ../src/.cherryci -s c-util
    - script:
        - ./vmrun -T i686 -- ../src/cherryci -d ../src/.cherryci -s c-util
